### ISSUE TITLE
How to Change has_many select label on Admin?

### ISSUE THREAD

**Issue by wbotelhos** [locomotivecms/engine#1059]
Hi, congrats for the great job. (:

I have the following relationship:

Category:

```yaml
- "1":
    name: Category One
```
Article:

```yaml
- "42":
    body: Body 42
    category: '1'
    title: Title 42
```

On admin the label displayed on `category` select search is `1`, but I want to display the name of the category. Is it possible? I tried to change the property `label_field_name` on content_type, but it still getting the `"1"` value.

I want to do that, because the ID does not change, but the name can changes. It will avoids migration on article relation if something changes.

**Comment by wbotelhos** [comment]
We can use `label_field_name` and choose the attribute we want.

Thanks!

**Comment by wbotelhos** [comment]
Some how, even when a change this fields to `name` or other, for example, I still see the numbers `"1"` on select box, not the value of `name` field.

**Comment by did** [comment]
hi @wbotelhos, try this instead:

```yaml
- "Category one"
```

Article:

```yaml
- "Title 42":
    body: Body 42
    category: category-one
```

That should do what you want.
