### ISSUE TITLE
Can't seem to get many_to_many to persist?

### ISSUE THREAD

**Issue by allanbreyes** [locomotivecms/engine#1066]
This is for v3.0.x @ master.  Is this a bug/issue, or is my syntax incorrect?

Here's the schema:

**Courses**
```yaml
slug: courses
label_field_name: key

fields:
- key:
    label: Key
    type: string
    required: true
    localized: false

- partners:
    label: Partners
    type: many_to_many
    class_name: partners
    inverse_of: courses
    ui_enabled: true
```

**Partners**
```yaml
slug: partners
label_field_name: key

fields:
- key:
    label: Key
    type: string
    required: false
    localized: false

- courses:
    label: Courses
    type: many_to_many
    class_name: courses
    inverse_of: partners
    ui_enabled: true
```

Here's some sample data:

`data/courses.yml`
```yaml
- "nd853":
    partners: [google]
```

`data/partners.yml`
```yaml
- "google":
    courses: [nd853]
```

---

Symptoms:
- Saving via admin dashboard does not persist data, on both local and production
- Fixture data not accessible in local, production, or wagon server:
  - e.g. `{{ contents.courses.first.partners.size }}` yields `0`
