### ISSUE TITLE
engine 3.0.0.rc4 accept `date_time` as `date` type

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/engine#1086]
Connected with #1085

REPRO
 - use wagon 2.0.0.rc4
```
    $ bundle exec wagon version
    2.0.0.rc4
```
 - create new project
 - create "content_type" `app/content_types/photos.yml`:
```
name: Photos
slug: photos
description: A description of the content type for the editors
label_field_name: name
order_by: posted_at
order_direction: desc

fields: 
- name: # The lowercase, underscored name of the field
    label: Name # Human readable name of the field
    type: string
    required: true
    hint: Explanatory text displayed in the back office
    localized: false

- posted_at: # The lowercase, underscored name of the field
    label: Posted at # Human readable name of the field
    type: date_time
    required: true
    hint: Explanatory text displayed in the back office
    localized: false
```
 - note we used **type: date_time**
 - prepare content_entry `data/photos.yml`:
```
- "Partner 1":
    posted_at: "2013-08-08 15:00:10"
```
 - install engine v3.0.0.rc4 locally. Gemfile of the engine:
```
source 'https://rubygems.org'
gem 'rails', '4.2.5'
#gem 'locomotivecms', '~> 3.0.0.rc4'
gem 'locomotivecms', require: 'locomotive/engine', git: 'https://github.com/locomotivecms/engine.git', ref: 'v3.0.0.rc4'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'puma'
group :development do
  # Unix
  gem 'therubyracer', require: 'v8', platforms: :ruby unless RUBY_PLATFORM.include?('darwin')
end
```
 - run engine locally
```
$ bundle exec rails server
=> Booting Puma
=> Rails 4.2.5 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Puma 2.15.3 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:3000
```
 - create new site & confgure `config/deploy.yml` in our project
 - push content_types & content_entries to the engine:
```
$ bundle exec wagon push test1 -v -d -r content_types content_entries
Pushing ContentTypes
 persisting Photos [done]
  persisting Photos [done]
  persisting Photos with relationships [skip]
  persisting Photos / Partner 1 [done]
```
 - wagon sends following data for `Photos` content_type:
```
{:name=>"Photos", :slug=>"photos", :description=>"A description of the content type for the editors", :label_field_name=>:name, :fields=>[{:name=>"name", :type=>"string", :label=>"Name", :hint=>"Explanatory text displayed in the back office", :required=>true, :localized=>false, :unique=>false, :position=>0}, {:name=>"posted_at", :type=>"date_time", :label=>"Posted at", :hint=>"Explanatory text displayed in the back office", :required=>true, :localized=>false, :unique=>false, :position=>1}], :order_by=>"posted_at", :order_direction=>"desc"}
```
WHATS WRONG
 - wagon sends following data for `Photos` content_entry - missed time:
```
{:_slug=>"partner-1", :name=>"Partner 1", :posted_at=>"2013-08-08"}
```
 - engine v3 does't accept `data_time` type of field

IT SHOULD BE
 - wagon should send following data for `Photos` content_entry:
```
{:_slug=>"partner-1", :name=>"Partner 1", :posted_at=>"2013-08-08 15:00:10"}
```
 - engine v3 should not accept `data_time` type of field

NOTE
 - if you want to see what wagon sends, debug (or edit file) `locomotivecms_wagon-2.0.0.rc4/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb`
