### ISSUE TITLE
`with_scope photo.ne: nil` returns 0 records - only Engine

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/engine#1093]
1. We have content_type `partners`
    ```
    name: Partners
    slug: partners
    description: "XXX"
    label_field_name: name
    order_by: manually
    order_direction: asc
    
    fields: 
    - name:
        label: Name
        type: string
        required: true
        hint: "Partner Name"
        localized: false

    - photo:
        label: "Photo"
        type: belongs_to
        required: false
        hint: "Partner's Logo"
        localized: false  
        class_name: photos
    ```
2. We have content_type `photos`
    ```
    name: "Photos"
    slug: photos
    description: "Photos .jpg, .png"
    label_field_name: name
    order_by: posted_at
    order_direction: desc

    fields: 
    - name: 
        label: Name
        type: string
        required: true
        hint: "Name"
        localized: false

    - posted_at:
        label: "Post at"
        type: date_time
        required: true
        hint: "Post at"
        localized: false

    - image:
        label: Image
        type: file
        required: true
        hint: "File (.jpg, .png)"
        localized: false

    - partners:
        label: Partner
        type: has_many
        required: false
        hint: "Partner assigned to this photo"
        localized: false
        class_name: partners
        inverse_of: photo
        ui_enabled: true
    ```
3. We want to filter Partners's photos that are not nil:

    ```
    {% with_scope photo.ne: nil %}
      {% assign images = contents.partners.all | map: 'photo' %}
    {% endwith_scope %}
    ```
4. We have defined some photos and partners data.

WHATS WRONG
  - the Engine returns 0 records (images.size is equal to zero)

IT SHOULD BE 
  - the Engine should return non-zero records (images.size should be greater to zero)

INFO
  - the Wagon works fine (images.size is greater to zero)
  - if we remove section `with_scope photo.ne: nil` the Engine returns non-empty array
  - gems used in the Engine (listed with `bundle | grep locomotive`):

    ```
    Using locomotivecms-liquid 4.0.0
    Using locomotivecms-solid 4.0.1
    Using locomotivecms_common 0.0.5
    Using locomotivecms_steam 1.0.0.rc8 from https://github.com/locomotivecms/steam.git (at master)
    Using locomotivecms 3.0.0.rc5 from https://github.com/locomotivecms/engine.git (at master)
    ```
  - gems used in the Wagon: 

    ```
    Using locomotivecms-liquid 4.0.0
    Using locomotivecms-solid 4.0.1
    Using locomotivecms_coal 1.0.0.rc3
    Using locomotivecms_common 0.0.5
    Using locomotivecms_steam 1.0.0.rc8 from https://github.com/locomotivecms/steam.git (at master)
    Using locomotivecms_wagon 2.0.0.rc5
    ```
