### ISSUE TITLE
select_options issue

### ISSUE THREAD

**Issue by nielsenramon** [locomotivecms/engine#1149]
When pushing a `select_option` content type it gives me the following error:

```
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_coal-1.2.0/lib/locomotive/coal/resources/concerns/request.rb:36:in `do_request'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_coal-1.2.0/lib/locomotive/coal/resources/concerns/request.rb:15:in `put'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_coal-1.2.0/lib/locomotive/coal/resources/base.rb:35:in `update_with_locale'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_content_entries_command.rb:42:in `persist'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:34:in `block in _push'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:30:in `each'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:30:in `_push'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_content_entries_command.rb:12:in `block in _push'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_content_entries_command.rb:10:in `each'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_content_entries_command.rb:10:in `_push'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:25:in `block in _push_with_timezone'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/core_ext/time/zones.rb:48:in `use_zone'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:24:in `_push_with_timezone'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:18:in `block in push'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:50:in `instrument'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:16:in `push'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:12:in `push'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_command.rb:55:in `block in _push'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_command.rb:84:in `block in each_resource'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_command.rb:77:in `each'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_command.rb:77:in `each_resource'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_command.rb:54:in `_push'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_command.rb:41:in `push'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_command.rb:31:in `push'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon.rb:73:in `push'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/cli.rb:318:in `deploy'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/bin/wagon:12:in `<top (required)>'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bin/wagon:23:in `load'
	/Users/nielsenramon/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bin/wagon:23:in `<main>'
```

This is my content type:

```
name: Stories
slug: stories
description: Stories
label_field_name: year
order_by: _position
order_direction: desc
public_submission_enabled: false
public_submission_account_emails: []
fields:
- year:
    label: Year
    type: integer
    required: true
    hint: Story year
    localized: false
- description:
    label: Description
    type: text
    required: false
    hint: Story description
    localized: true
- image:
    label: Image
    type: file
    required: true
    hint: Story picture
    localized: false
- image_size:
    label: Image size
    type: select
    required: false
    hint: Image size
    localized: false
    select_options:
    - large
    - small
    - medium
- color:
    label: Background color
    type: select
    required: false
    hint: Background color
    localized: false
    select_options:
    - blue
    - red
    - brown
```

The data file:

```
- '2015':
    _slug: 2015
    year: 2015
    description: test
    image: "/samples/content_entries/picture.jpg"
    image_size: medium
    color: brown
```

So I am unable to push content types with the select type in them to production if it already has been pushed. The workaround now is to delete the content type from production and repush everything with the data. But that is not a really good one :)

It probably has something to do with the localization.
