### ISSUE TITLE
type: select localisation issue?

### ISSUE THREAD

**Issue by nielsenramon** [locomotivecms/engine#1151]
I think this is a localisation issue. Follow me along:

My content type: 

```
- period:
    label: Period
    type: select
    required: true
    hint: Tijd van de dag
    localized: true
    select_options:
      nl:
      - Voormiddag
      - Namiddag
      fr:
      - Voormiddag
      - Namiddag
      en:
      - Voormiddag
      - Namiddag
```

Data:

```
- Maandag namiddag:
    _slug:
      nl: maandag-nm
      en: maandag-nm
      fr: maandag-nm
    name:
      nl: Maandag namiddag
      en: Maandag namiddag
      fr: Maandag namiddag
    period:
      nl: Namiddag
      en: Namiddag
      fr: Namiddag
    ruiming_locaties:
    - aalter
    - adegem
    - knesselare
    - ursel
    - maldegem
```

This does not push (undefined method join). Once I remove the translations it does however push without issues. Once i pull this back in (wagon pull) it also errors.

I do not have this issue with untranslated select types.

Any idea what I am doing wrong?
