### ISSUE TITLE
Deploying localized categories content entry'name field is ignored if label_field_name is set to name

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/engine#1157]
**REPRO**

**1. I have `categories` content entry defined like that**:

```
name: Categories
slug: categories
description: Categories
label_field_name: name
order_by: manually

fields: 
- name: 
    label: Name
    type: string
    required: true
    hint: Name
    localized: true

- description: 
    label: Description
    type: text
    required: true
    hint: Description
    localized: false
    text_formatting: text 
```
Important thinks: 
 - `name` field is localized (true) and set for `label_field_name`

**2. I have defined categories data like that**:
```
- "Wystawa":
    _slug:
      pl: wystawa
      en: wystawa
    name:
      pl: Moja Wystawa
      em: Art Exhibition
    description: "Wystawa organizowana przez PGS"

- "Relacja":
    _slug:
      pl: relacja
      en: relacja
    name:
      pl: Foto Relacja
      em: Photorelation
    description: "Relacja fotograficzna organizowana przez PGS"
```
Note:
  - I want the same slug for both polish and english (useful for with_scope)
  -  I have defined `name` values because `name` field is localized

**3. Let's deploy**
```
bundle exec wagon push my_project -v -d -r content_entries -f categories
```

**WHAT'S WRONG?**

1. In the back-office we'll get categories "Wystawa" and "Relacja" both for pl and en

**IT SHOULD BE**

1. I expect to get categories:
  -  (Moja Wystawa, Foto Relacja) for pl
  - (Art Exhibition, Photorelation) for en

**NOTE**
I've tried to translate categories in the back-office and download it with the Wagon.
Downloaded `categories.yml` file was the same as I used for deploying.

**QUESTION**
What's wrong?
If I download the site and use it for deploying, translated fields data will be lost?

I use the **Wagon 2.1.1** & the **Engine 3.1.1** version
