### ISSUE TITLE
[Locomotive Editor] NoMethodError thrown on personalized Content Type

### ISSUE THREAD

**Issue by kikito** [locomotivecms/engine#119]
Hi there,

This is a LocomotiveEditor issue. I didn't know there to put them, so I'm creating them here. Please let me know if there's a better place for that.

I'm trying to create a site with some content types besides pages using LE. I'm mimicking what the "Lawyer and Attorney" does on its database.yml file (on LE it's called site.yml)

This is a (redacted) copy of what I have on my site.yml file:

```
pages:
  - index:
      title: "Home Page"
      published: true
  - 404:
      title: "Page not found"
  ...


content_types:
  Banner:
    description: "Banner being shown on the footer"
    slug: banner
    api_enabled: false
    order_by: manually
    highlighted_field_name: alt
    fields:
      - alt:
          hint: "Appears on mouseover"
      - url:
          hint: "Where does the banner link to"
      - image:
          kind: file
          hint: "Must have 250x100 pixels"
    contents:
      - first_banner:
          - alt: Alt of the first banner
          - url: http://google.com
          - imagen: "/samples/contents/banner.png"
```

When I try to access this banner with `contents.banner.first`, I get this error:

```
NoMethodError - undefined method `contents' for nil:NilClass:
[..]/gems/locomotive_editor-0.1.2/lib/locomotive/liquid/drops/contents.rb:63:in `collection'
[..]/gems/locomotive_editor-0.1.2/lib/locomotive/liquid/drops/contents.rb:21:in `first'
[..]/gems/locomotive_liquid-2.2.2/lib/liquid/drop.rb:35:in `invoke_drop'
[..]/gems/locomotive_liquid-2.2.2/lib/liquid/context.rb:230:in `lookup_and_evaluate'
...
```

Is the syntax I'm using correct? Where is the error?
