### ISSUE TITLE
Allow text metafields with raw formating

### ISSUE THREAD

**Issue by DonKoko** [locomotivecms/engine#1283]
Currently when creating a metafield with type text, it only allows to use html.
It would be great to have the option to chose the format, so we can use it for example for 3rd party scripts. I would suggest to follow the same standard as everywhere else in Loco, so the definition will look something like this:
```
footer_scripts:
  label: Footer scripts
  fields:
    scripts: 
      type: text
      format: raw
```
