### ISSUE TITLE
Rename General Settings to Site Administration

### ISSUE THREAD

**Issue by westonganger** [locomotivecms/engine#1299]
I propose that the `General Settings` sidebar section be renamed to `Site Administration`

My reasoning:

A. they seems like administrative settings / tasks. 
B. My language preference would be to use a string like `Site Settings` or `General Settings` instead of `Properties`

My Updated Locale (for `en` but could be adapted for all other untranslated languages)

```yaml
en:
  locomotive:
    shared:
      sidebar:
        settings: Site Administration # was "General Settings"
    current_site:
      edit:
        title: Site Administration # was "Editing the current site"
```
