### ISSUE TITLE
Add ability to add custom page settings

### ISSUE THREAD

**Issue by westonganger** [locomotivecms/engine#1320]
Currently the page settings section is quite limited.

![Screenshot from 2019-05-29 12-02-34](https://user-images.githubusercontent.com/3414795/58584378-03b5ad80-820b-11e9-844b-77932bb1bfeb.png)

It would be nice to be able to add custom settings for pages. This would solve the original request from #1308. 

```
---
title: My Page
settings:
  setting_one:
    label: "Setting One"
    type: string
    default: 
```
