### ISSUE TITLE
has_many target is not exported correctly

### ISSUE THREAD

**Issue by mscottford** [locomotivecms/engine#165]
Here's an example of how has_many fields are currently exported:

```
- events:
    kind: has_many
    label: Events
    target: ContentContentType4e42aa138721650001000009
```

The target's stub should be used instead of the target's class name. Expected output should look like the following:

```
- events:
    kind: has_many
    label: Events
    target: athletic_events
```
