### ISSUE TITLE
Lcomotivehosting ui bug (doesn't really belong here I know)

### ISSUE THREAD

**Issue by manuchap** [locomotivecms/engine#758]
Tried LocomotiveHosting and found a few bugs:
Changing the UI Language sends an non-secure request (http instead of https) which throws a 404.
Pushing a site with:

```
hosting:
  host: spr.locomotivehosting.com
  api_key: 762d700f etc.
  ssl: true
```

gives me:

```
unable to get an API token: 757: unexpected token at 'Content of the 404 page'
```

Maybe it's because it's not published but it's not what the doc says.
