### ISSUE TITLE
with_scope and boolean variables

### ISSUE THREAD

**Issue by maffy420** [locomotivecms/engine#852]
I'm new to locomotive, but couldn't find this issue reported elsewhere.

Here's my content_type (slightly elided):

```
fields: 
- name: # Name of the field
    label: Name
    type: string
    required: true
    hint: Guest full name
    localized: false

- correspondent: # Name of the field
    label: Correspondent
    type: boolean
    required: true
    hint: Is this guest an irregular correspondent?
    localized: false
```

I've noticed that I can do this to display all the guests with the "correspondent" field set to "true."

```
{% assign value = true %} 
{% with_scope correspondent: value, order_by: 'name' %}
  {% for guest in contents.guests %}
     {{ guest.name }}
  {% endfor %}
{% endwith_scope %}
```

However, if I do the following, rather than getting all the guests with "correspondent" set to "false," I get no guests at all.

```
{% assign value = false %} 
{% with_scope correspondent: value, order_by: 'name' %}
  {% for guest in contents.guests %}
    {{ guest.name }}
  {% endfor %}
{% endwith_scope %}
```

It does work if instead of using a boolean variable, I simply put "false" in the with_scope, like so:

```
{% with_scope correspondent: false, order_by: 'name' %}
  {% for guest in contents.guests %}
    {{ guest.name }}
  {% endfor %}
{% endwith_scope %}
```

I'm not sure how booleans are treated in locomotive exactly, but it seems like an issue in with_scope.
