### ISSUE TITLE
AmbiguousRelationship error having two relationships between the same content types

### ISSUE THREAD

**Issue by matus-tomlein** [locomotivecms/engine#884]
I have the following content types:

**Teams**
```
fields:
- games_won:
    label: Games won
    type: has_many
    target: games
    inverse_of: winners
    ui_enabled: true
- games_lost:
    label: Games lost
    type: has_many
    target: games
    inverse_of: losers
    ui_enabled: true
```

**Games**
```
fields:
- winners:
    label: Winners
    type: belongs_to
    target: teams
    inverse_of: games_won
- losers:
    label: Losers
    type: belongs_to
    target: teams
    inverse_of: games_lost
```

When I try to insert a new item into games with some specified teams, it returns the error:
```
Mongoid::Errors::AmbiguousRelationship in Locomotive/content_entries#edit
Problem:
  Ambiguous relations "games_won", "games_lost" defined on Locomotive::ContentEntry530e50bb9ebea4d0ba00000d.
Summary:
  When Mongoid attempts to set an inverse document of a relation in memory, it needs to know which relation it belongs to. When setting :winners, Mongoid looked on the class Locomotive::ContentEntry530e50bb9ebea4d0ba000007 for a matching relation, but multiples were found that could potentially match: "games_won", "games_lost".
Resolution:
  On the :winners relation on Locomotive::ContentEntry530e50bb9ebea4d0ba000007 you must add an :inverse_of option to specify the exact relationship on Locomotive::ContentEntry530e50bb9ebea4d0ba00000d that is the opposite of :winners.
```

I have tried this multiple times, I also tried to define the content types in the admin interface.
In the admin interface, it does not allow me to specify the inverse_of attribute for belongs_to fields. It probably also ignores the inverse_of attribute I specified for the winners and losers fields in Games.

Using wagon 1.4.0, rails 3.2.17 with ruby 2.1.0 and mongo 2.4.9 on the engine.
