### ISSUE TITLE
locomotivehosting missing translation string (fr)

### ISSUE THREAD

**Issue by manuchap** [locomotivecms/engine#908]
…for almost in datetime distance_in_words:
_config->locales->fr.yml_

``` yml
fr:
  datetime:
    distance_in_words:
      almost_x_years:
        one: presque 1 an
        other: presque %{count} ans
```
