### ISSUE TITLE
Fonts, S3, and CSS -- How do I get the asset path?

### ISSUE THREAD

**Issue by meskyanichi** [locomotivecms/engine#948]
Consider the following SymbolSet CSS snippet. This is trying to look for fonts using a relative path. I'm hosting on Heroku and my assets (including fonts) are stored on S3. How can I render the asset path in CSS?

```css
@font-face {
  font-family: "SSStandard";
  src: url('ss-standard.eot');
  src: url('ss-standard.eot?#iefix') format('embedded-opentype'),
       url('ss-standard.woff') format('woff'),
       url('ss-standard.ttf')  format('truetype'),
       url('ss-standard.svg#SSStandard') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

In Rails, I do it like so, using `.css.erb`:

```css
@font-face {
  font-family: "SSStandard";
  src: url('<%= asset_path("ss-standard.eot") %>');
  src: url('<%= asset_path("ss-standard.eot") %>?#iefix') format('embedded-opentype'),
       url('<%= asset_path("ss-standard.woff") %>') format('woff'),
       url('<%= asset_path("ss-standard.ttf") %>')  format('truetype'),
       url('<%= asset_path("ss-standard.svg") %>#SSStandard') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

How would you do this with LocomotiveCMS?

Thanks!
