### ISSUE TITLE
Unable to push related content type entries

### ISSUE THREAD

**Issue by anja98** [locomotivecms/engine#972]
I'm using wagon 1.4.0 and engine 2.4.1

Following instructions from http://doc.locomotivecms.com/making-blog/3-5-related-types, I've created Posts and Comments with the relationship of a post has many comments.

posts.yml
```
name: Posts
slug: posts
description: A description of the content type for the editors
label_field_name: title
order_by: manually 
fields: 
- title: 
    label: Title
    type: string
    required: true
    hint: A description of the field for the editors
    localized: false
- comments: 
    label: Comments
    type: has_many
    required: false
    localized: false
    class_name: comments
    inverse_of: post  
    ui_enabled: true 
```

comments.yml
```
name: Comments
slug: comments
description: A description of the content type for the editors
label_field_name: message
order_by: manually 
fields: 
- message: 
    label: Message
    type: string
    required: true
    hint: A description of the field for the editors
    localized: false
- post: 
    label: Post
    type: belongs_to
    required: true
    hint: A description of the field for the editors
    localized: false
    class_name: posts
```

Heres how the sample data look like:
data/posts.yml
```
- "Sample 1"

- "Sample 2"

- "Sample 3"

- "Sample 4"
```

data/comments.yml
```
- "Sample 1":
    message: "This is a message"
    post: sample-1 # Permalink of the target entry

- "Sample 2":
    message: "This is a message"
    post: sample-2 # Permalink of the target entry

- "Sample 3":
    message: "This is a message"
    post: sample-3 # Permalink of the target entry

- "Sample 4":
    message: "This is a message"
    post: sample-4 # Permalink of the target entry
```

I've tried adding the relationship through the engine backend and pulling it back to wagon. Deleted the backend model and push it back to force a re-create using the engine generaged yml, I enocounter the same error as well.

This seems to be a bug?
